AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    FastAPI aws lambda example
Resources:
    CRLapiLambda:
        Type: AWS::Serverless::Function
        Properties:
            Events:
                ApiEvent:
                    Properties:
                        RestApiId:
                            Ref: CRLapiGateway
                        Path: /{proxy+}
                        Method: ANY
                    Type: Api
            FunctionName: UW-CRL-Api-v1
            CodeUri: ./
            Handler: app.main.handler
            Runtime: python3.12
            Timeout: 300 # timeout of your lambda function
            Environment:
              Variables:
                PG_DBNAME: /api/v1/db_name
                PG_USER: /api/v1/db_user
                PG_PASSWORD: /api/v1/db_pw
                PG_HOST: /api/v1/db_host
                S3_BUCKET: /api/v1/s3_bucket
                S3_BASE_PREFIX_USER_DOWNLOADS: /api/v1/s3_prefix_user_downloads
                DATA_SIZE_RETURN_LIMIT_MB: /api/v1/data_size_return_limit_mb
            MemorySize: 128 # memory size of your lambda function
            Description: UW CRL API v1
            # other options, see ->
            # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-template-anatomy-globals.html#sam-specification-template-anatomy-globals-supported-resources-and-properties
            Role: !Sub arn:aws:iam::${AWS::AccountId}:role/uw-crl-lambda-api

    CRLapiGateway:
        Type: AWS::Serverless::Api
        Properties:
            StageName: v1-dev
            OpenApiVersion: '3.0.0'